# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-28 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20171227_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=300, verbose_name='商品名'),
        ),
    ]
