# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 18:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0002_auto_20171227_0001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLeavingMesage',
            new_name='UserLeavingMessage',
        ),
    ]
