# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-30 18:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20171228_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfav',
            name='goods',
            field=models.ForeignKey(help_text='商品id', on_delete=django.db.models.deletion.CASCADE, related_name='text', to='goods.Goods', verbose_name='商品'),
        ),
    ]
